# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d01b95afb0567f86d05f708b403c647c0e89985a453c08f75e68448d256e74ff66c27118cc222b9da1713d2200090c5ad5533f481e1c0aa8b81a11db3218036

test:
  secret_key_base: ab776591407c28471ef3ccead9326b4ee094a709a80458eaa20dd6c4b1c3339a8261680d7df60aa865a906d60e29c26c4b3a2c84131bcf6ae5a66d1175414014

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
